version: '2'

linters:
  enable-all: true
  disable:
    - exhaustruct    # too noisy for zero value structs
    - forbidigo      # I print output on purpose sometimes
    - godox          # saving todos till another validation step
    - ireturn        # I like generic return types
    - nonamedreturns # I like named returns
    - wsl            # deprecated

linters-settings:
  depguard:
    rules:
      all:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/magefile/mage
          - github.com/magefile/mage/mg
          - github.com/magefile/mage/sh
      test:
        files:
          - $test
        allow:
          - $gostd

  nlreturn:
    block-size: 2

  unused:
    field-writes-are-uses: false
    exported-fields-are-used: false
    local-variables-are-used: false

issues:
  fix: true
  exclude-generated: lax
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-rules:
    # Dynamic errors are acceptable and often clearer in test code/predicates.
    - path: _test\.go
      source: ".*"
      linters:
        - err113

