//nolint:testpackage // Internal test - needs access to unexported screen internals
package screens

// Note: TestSyncScreen_DebugLogging tests removed - debug logging moved to AnalysisScreen
// The [DISPLAY] log messages are now generated by AnalysisScreen.renderCurrentlyCopying()
