// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	syncengine "github.com/joe/copy-files/internal/syncengine"
	_imptest "github.com/toejough/imptest/imptest"
	time "time"
)

// TimeProviderMock is the mock for TimeProvider.
type TimeProviderMock struct {
	imp       *_imptest.Imp
	Now       *_imptest.DependencyMethod
	NewTicker *TimeProviderMockNewTickerMethod
}

// Interface returns the TimeProvider implementation that can be passed to code under test.
func (m *TimeProviderMock) Interface() syncengine.TimeProvider {
	return &mockTimeProviderImpl{mock: m}
}

// TimeProviderMockNewTickerArgs holds typed arguments for NewTicker.
type TimeProviderMockNewTickerArgs struct {
	D time.Duration
}

// TimeProviderMockNewTickerCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimeProviderMockNewTickerCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TimeProviderMockNewTickerCall) GetArgs() TimeProviderMockNewTickerArgs {
	raw := c.RawArgs()
	return TimeProviderMockNewTickerArgs{
		D: raw[0].(time.Duration),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimeProviderMockNewTickerCall) InjectReturnValues(result0 syncengine.Ticker) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TimeProviderMockNewTickerMethod wraps DependencyMethod with typed returns.
type TimeProviderMockNewTickerMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *TimeProviderMockNewTickerMethod) Eventually() *TimeProviderMockNewTickerMethod {
	return &TimeProviderMockNewTickerMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TimeProviderMockNewTickerMethod) ExpectCalledWithExactly(d time.Duration) *TimeProviderMockNewTickerCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(d)
	return &TimeProviderMockNewTickerCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TimeProviderMockNewTickerMethod) ExpectCalledWithMatches(matchers ...any) *TimeProviderMockNewTickerCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TimeProviderMockNewTickerCall{DependencyCall: call}
}

// TimeProviderMockNowCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimeProviderMockNowCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimeProviderMockNowCall) InjectReturnValues(result0 time.Time) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockTimeProvider creates a new TimeProviderMock for testing.
func MockTimeProvider(t _imptest.TestReporter) *TimeProviderMock {
	imp := _imptest.NewImp(t)
	return &TimeProviderMock{
		imp:       imp,
		Now:       _imptest.NewDependencyMethod(imp, "Now"),
		NewTicker: &TimeProviderMockNewTickerMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "NewTicker")},
	}
}

// mockTimeProviderImpl implements syncengine.TimeProvider.
type mockTimeProviderImpl struct {
	mock *TimeProviderMock
}

// NewTicker implements syncengine.TimeProvider.NewTicker.
func (impl *mockTimeProviderImpl) NewTicker(d time.Duration) syncengine.Ticker {
	call := &_imptest.GenericCall{
		MethodName:   "NewTicker",
		Args:         []any{d},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 syncengine.Ticker
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(syncengine.Ticker); ok {
			result1 = value
		}
	}

	return result1
}

// Now implements syncengine.TimeProvider.Now.
func (impl *mockTimeProviderImpl) Now() time.Time {
	call := &_imptest.GenericCall{
		MethodName:   "Now",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 time.Time
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(time.Time); ok {
			result1 = value
		}
	}

	return result1
}
