// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	syncengine "github.com/joe/copy-files/internal/syncengine"
	_imptest "github.com/toejough/imptest/imptest"
	time "time"
)

// TimeProviderMockHandle is the test handle for TimeProvider.
type TimeProviderMockHandle struct {
	Mock       syncengine.TimeProvider
	Method     *TimeProviderMockMethods
	Controller *_imptest.Imp
}

// TimeProviderMockMethods holds method wrappers for setting expectations.
type TimeProviderMockMethods struct {
	Now       *_imptest.DependencyMethod
	NewTicker *TimeProviderMockNewTickerMethod
}

// TimeProviderMockNewTickerArgs holds typed arguments for NewTicker.
type TimeProviderMockNewTickerArgs struct {
	D time.Duration
}

// TimeProviderMockNewTickerCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimeProviderMockNewTickerCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *TimeProviderMockNewTickerCall) GetArgs() TimeProviderMockNewTickerArgs {
	raw := c.RawArgs()
	return TimeProviderMockNewTickerArgs{
		D: raw[0].(time.Duration),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimeProviderMockNewTickerCall) InjectReturnValues(result0 syncengine.Ticker) {
	c.DependencyCall.InjectReturnValues(result0)
}

// TimeProviderMockNewTickerMethod wraps DependencyMethod with typed returns.
type TimeProviderMockNewTickerMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *TimeProviderMockNewTickerMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *TimeProviderMockNewTickerMethod) ExpectCalledWithExactly(d time.Duration) *TimeProviderMockNewTickerCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(d)
	return &TimeProviderMockNewTickerCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *TimeProviderMockNewTickerMethod) ExpectCalledWithMatches(matchers ...any) *TimeProviderMockNewTickerCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &TimeProviderMockNewTickerCall{DependencyCall: call}
}

// TimeProviderMockNowCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type TimeProviderMockNowCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *TimeProviderMockNowCall) InjectReturnValues(result0 time.Time) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockTimeProvider creates a new TimeProviderMockHandle for testing.
func MockTimeProvider(t _imptest.TestReporter) *TimeProviderMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &TimeProviderMockMethods{
		Now:       _imptest.NewDependencyMethod(ctrl, "Now"),
		NewTicker: newTimeProviderMockNewTickerMethod(_imptest.NewDependencyMethod(ctrl, "NewTicker")),
	}
	h := &TimeProviderMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockTimeProviderImpl{handle: h}
	return h
}

// mockTimeProviderImpl implements syncengine.TimeProvider.
type mockTimeProviderImpl struct {
	handle *TimeProviderMockHandle
}

// NewTicker implements syncengine.TimeProvider.NewTicker.
func (impl *mockTimeProviderImpl) NewTicker(d time.Duration) syncengine.Ticker {
	call := &_imptest.GenericCall{
		MethodName:   "NewTicker",
		Args:         []any{d},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 syncengine.Ticker
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(syncengine.Ticker); ok {
			result1 = value
		}
	}

	return result1
}

// Now implements syncengine.TimeProvider.Now.
func (impl *mockTimeProviderImpl) Now() time.Time {
	call := &_imptest.GenericCall{
		MethodName:   "Now",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 time.Time
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(time.Time); ok {
			result1 = value
		}
	}

	return result1
}

// newTimeProviderMockNewTickerMethod creates a typed method wrapper with Eventually initialized.
func newTimeProviderMockNewTickerMethod(dm *_imptest.DependencyMethod) *TimeProviderMockNewTickerMethod {
	m := &TimeProviderMockNewTickerMethod{DependencyMethod: dm}
	m.Eventually = &TimeProviderMockNewTickerMethod{DependencyMethod: dm.Eventually}
	return m
}
