// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
	_testing "testing"
)

// EngineAnalyze wraps a callable function for testing.
// Create with NewEngineAnalyze(t, yourFunction), call Start() to execute,
// then use ExpectReturnedValuesAre/Should() or ExpectPanicWith() to verify behavior.
type EngineAnalyze struct {
	*_imptest.CallableController[EngineAnalyzeReturn]
	callable func() error
}

// NewEngineAnalyze creates a new wrapper for testing the callable function.
// Pass the function to test and a testing.TB to enable assertion failures.
//
// Example:
//
//	wrapper := NewEngineAnalyze(t, myFunction)
//	wrapper.Start(args...).ExpectReturnedValuesAre(expectedVals...)
func NewEngineAnalyze(t _testing.TB, callable func() error) *EngineAnalyze {
	return &EngineAnalyze{
		CallableController: _imptest.NewCallableController[EngineAnalyzeReturn](t),
		callable:           callable,
	}
}

// ExpectPanicWith asserts the callable panicked with a value matching the expectation.
// Use imptest.Any() to match any panic value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if the callable returned normally or panicked with a different value.
func (s *EngineAnalyze) ExpectPanicWith(expected any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Panicked != nil {
		ok, msg := _imptest.MatchValue(s.Panicked, expected)
		if !ok {
			s.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnedValuesAre asserts the callable returned with exactly the specified values.
// Fails the test if the values don't match exactly or if the callable panicked.
// Uses == for comparison, so reference types must be the same instance.
func (s *EngineAnalyze) ExpectReturnedValuesAre(v1 error) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		if !_reflect.DeepEqual(s.Returned.Result0, v1) {
			s.T.Fatalf("expected return value 0 to be %v, got %v", v1, s.Returned.Result0)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// ExpectReturnedValuesShould asserts return values match the given matchers.
// Use imptest.Any() to match any value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if any matcher fails or if the callable panicked.
func (s *EngineAnalyze) ExpectReturnedValuesShould(v1 any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(s.Returned.Result0, v1)
		if !ok {
			s.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// Start begins execution of the callable in a goroutine with the provided arguments.
// Returns the wrapper for method chaining with expectation methods.
// Captures both normal returns and panics for verification.
//
// Example:
//
//	wrapper.Start(arg1, arg2).ExpectReturnedValuesAre(expectedResult)
func (s *EngineAnalyze) Start() *EngineAnalyze {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				s.PanicChan <- r
			}
		}()

		ret0 := s.callable()
		s.ReturnChan <- EngineAnalyzeReturn{
			Result0: ret0,
		}
	}()
	return s
}

// EngineAnalyzeResponse represents the response from the callable (either return or panic).
// Check EventType to determine if the callable returned normally or panicked.
// Access ReturnVal for return values or PanicVal for panic information.
type EngineAnalyzeResponse struct {
	EventType string // "return" or "panic"
	ReturnVal *EngineAnalyzeReturn
	PanicVal  any
}

// Type returns the event type: "return" for normal returns, "panic" for panics.
func (r *EngineAnalyzeResponse) Type() string {
	return r.EventType
}

// EngineAnalyzeReturn holds the return values from the callable function.
// Access individual return values via Result0, Result1, etc. fields.
type EngineAnalyzeReturn struct {
	Result0 error
}
