// Code generated by impgen. DO NOT EDIT.

package syncengine

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// WrapEngineCancelReturnsReturn holds the return values from the wrapped function.
type WrapEngineCancelReturnsReturn struct {
}

// WrapEngineCancelWrapper wraps a function for testing.
type WrapEngineCancelWrapper struct {
	*_imptest.CallableController[WrapEngineCancelReturnsReturn]
	callable func()
}

// ExpectCompletes verifies the function completes without panicking.
func (w *WrapEngineCancelWrapper) ExpectCompletes() {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		w.T.Fatalf("expected function to complete, but it panicked with: %v", w.Panicked)
	}
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapEngineCancelWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapEngineCancelWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// Start executes the wrapped function in a goroutine.
func (w *WrapEngineCancelWrapper) Start() *WrapEngineCancelWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		w.callable()
		w.ReturnChan <- WrapEngineCancelReturnsReturn{}
	}()
	return w
}

// WrapEngineCancel wraps a function for testing.
func WrapEngineCancel(t _imptest.TestReporter, fn func()) *WrapEngineCancelWrapper {
	return &WrapEngineCancelWrapper{
		CallableController: _imptest.NewCallableController[WrapEngineCancelReturnsReturn](t),
		callable:           fn,
	}
}
