// Code generated by impgen. DO NOT EDIT.

package syncengine

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapEngineEnableFileLoggingReturnsReturn holds the return values from the wrapped function.
type WrapEngineEnableFileLoggingReturnsReturn struct {
	Result0 error
}

// WrapEngineEnableFileLoggingWrapper wraps a function for testing.
type WrapEngineEnableFileLoggingWrapper struct {
	*_imptest.CallableController[WrapEngineEnableFileLoggingReturnsReturn]
	callable func(string) error
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapEngineEnableFileLoggingWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapEngineEnableFileLoggingWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapEngineEnableFileLoggingWrapper) ExpectReturnsEqual(v0 error) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapEngineEnableFileLoggingWrapper) ExpectReturnsMatch(v0 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapEngineEnableFileLoggingWrapper) Start(logPath string) *WrapEngineEnableFileLoggingWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0 := w.callable(logPath)
		w.ReturnChan <- WrapEngineEnableFileLoggingReturnsReturn{Result0: ret0}
	}()
	return w
}

// WrapEngineEnableFileLogging wraps a function for testing.
func WrapEngineEnableFileLogging(t _imptest.TestReporter, fn func(string) error) *WrapEngineEnableFileLoggingWrapper {
	return &WrapEngineEnableFileLoggingWrapper{
		CallableController: _imptest.NewCallableController[WrapEngineEnableFileLoggingReturnsReturn](t),
		callable:           fn,
	}
}
