// Code generated by impgen. DO NOT EDIT.

package syncengine

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// WrapEngineCloseLogReturnsReturn holds the return values from the wrapped function.
type WrapEngineCloseLogReturnsReturn struct {
}

// WrapEngineCloseLogWrapper wraps a function for testing.
type WrapEngineCloseLogWrapper struct {
	*_imptest.CallableController[WrapEngineCloseLogReturnsReturn]
	callable func()
}

// ExpectCompletes verifies the function completes without panicking.
func (w *WrapEngineCloseLogWrapper) ExpectCompletes() {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		w.T.Fatalf("expected function to complete, but it panicked with: %v", w.Panicked)
	}
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapEngineCloseLogWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapEngineCloseLogWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// Start executes the wrapped function in a goroutine.
func (w *WrapEngineCloseLogWrapper) Start() *WrapEngineCloseLogWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		w.callable()
		w.ReturnChan <- WrapEngineCloseLogReturnsReturn{}
	}()
	return w
}

// WrapEngineCloseLog wraps a function for testing.
func WrapEngineCloseLog(t _imptest.TestReporter, fn func()) *WrapEngineCloseLogWrapper {
	return &WrapEngineCloseLogWrapper{
		CallableController: _imptest.NewCallableController[WrapEngineCloseLogReturnsReturn](t),
		callable:           fn,
	}
}
