// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import _imptest "github.com/toejough/imptest/imptest"
import _reflect "reflect"
import _testing "testing"
import _time "time"
import syncengine "github.com/joe/copy-files/internal/syncengine"
import time "time"

// TimeProviderImp is the test controller for mocking the interface.
// Create with NewTimeProviderImp(t), then use Mock field to get the mock implementation
// and ExpectCallIs field to set expectations for method calls.
//
// Example:
//
//	imp := NewTimeProviderImp(t)
//	go codeUnderTest(imp.Mock)
//	imp.ExpectCallIs.MethodName().ExpectArgsAre(...).InjectResult(...)
type TimeProviderImp struct {
	*_imptest.Controller[*TimeProviderImpCall]
	Mock         *TimeProviderImpMock
	ExpectCallIs *TimeProviderImpExpectCallIs
	currentCall  *TimeProviderImpCall
}

// NewTimeProviderImp creates a new test controller for mocking the interface.
// The returned controller manages mock expectations and response injection.
// Pass t to enable automatic test failure on unexpected calls or timeouts.
//
// Example:
//
//	imp := NewTimeProviderImp(t)
//	go codeUnderTest(imp.Mock)
//	imp.ExpectCallIs.Method().ExpectArgsAre(...).InjectResult(...)
func NewTimeProviderImp(t *_testing.T) *TimeProviderImp {
	imp := &TimeProviderImp{
		Controller: _imptest.NewController[*TimeProviderImpCall](t),
	}
	imp.Mock = &TimeProviderImpMock{imp: imp}
	imp.ExpectCallIs = &TimeProviderImpExpectCallIs{imp: imp}
	return imp
}

// GetCurrentCall returns the current call being processed.
// If no call is pending, waits indefinitely for the next call.
// Returns the existing current call if it hasn't been completed yet.
func (i *TimeProviderImp) GetCurrentCall() *TimeProviderImpCall {
	if i.currentCall != nil && !i.currentCall.Done() {
		return i.currentCall
	}
	i.currentCall = i.GetCall(0, func(c *TimeProviderImpCall) bool { return true })
	return i.currentCall
}

// Within configures a timeout for expectations and returns a TimeProviderImpTimed for method chaining.
// The timeout applies to subsequent expectation calls.
//
// Example:
//
//	imp.Within(100*_time.Millisecond).ExpectCallIs.Method().ExpectArgsAre(...)
func (i *TimeProviderImp) Within(d _time.Duration) *TimeProviderImpTimed {
	return &TimeProviderImpTimed{
		ExpectCallIs: &TimeProviderImpExpectCallIs{imp: i, timeout: d},
	}
}

// TimeProviderImpCall represents a captured call to any method.
// Only one method field is non-nil at a time, indicating which method was called.
// Use Name() to identify the method and As{{Method}() to access typed call details.
type TimeProviderImpCall struct {
	now       *TimeProviderImpNowCall
	newTicker *TimeProviderImpNewTickerCall
}

// AsNewTicker returns the call cast to TimeProviderImpNewTickerCall for accessing call details.
// Returns nil if the call was not to NewTicker.
func (c *TimeProviderImpCall) AsNewTicker() *TimeProviderImpNewTickerCall {
	return c.newTicker
}

// AsNow returns the call cast to TimeProviderImpNowCall for accessing call details.
// Returns nil if the call was not to Now.
func (c *TimeProviderImpCall) AsNow() *TimeProviderImpNowCall {
	return c.now
}

// Done returns true if the call has been completed (response injected).
// Used internally to track call state.
func (c *TimeProviderImpCall) Done() bool {
	if c.now != nil {
		return c.now.done
	}
	if c.newTicker != nil {
		return c.newTicker.done
	}
	return false
}

// Name returns the name of the method that was called.
// Returns an empty string if the call struct is invalid.
func (c *TimeProviderImpCall) Name() string {
	if c.now != nil {
		return "Now"
	}
	if c.newTicker != nil {
		return "NewTicker"
	}
	return ""
}

// TimeProviderImpExpectCallIs provides methods to set expectations for specific method calls.
// Each method returns a builder for fluent expectation configuration.
// Use Within() on the parent TimeProviderImp to configure timeouts.
type TimeProviderImpExpectCallIs struct {
	imp     *TimeProviderImp
	timeout _time.Duration
}

// NewTicker returns a builder for setting expectations on NewTicker method calls.
func (e *TimeProviderImpExpectCallIs) NewTicker() *TimeProviderImpNewTickerBuilder {
	return &TimeProviderImpNewTickerBuilder{imp: e.imp, timeout: e.timeout}
}

// Now returns a builder for setting expectations on Now method calls.
func (e *TimeProviderImpExpectCallIs) Now() *TimeProviderImpNowBuilder {
	return &TimeProviderImpNowBuilder{imp: e.imp, timeout: e.timeout}
}

// TimeProviderImpMock provides the mock implementation of the interface.
// Pass TimeProviderImpMock to code under test that expects the interface implementation.
// Use the parent TimeProviderImp controller to set expectations and inject responses.
type TimeProviderImpMock struct {
	imp *TimeProviderImp
}

// NewTicker implements the interface method and records the call for testing.
// The method blocks until a response is injected via the test controller.
func (m *TimeProviderImpMock) NewTicker(d time.Duration) syncengine.Ticker {
	responseChan := make(chan TimeProviderImpNewTickerCallResponse, 1)

	call := &TimeProviderImpNewTickerCall{
		responseChan: responseChan,
		d:            d,
		t:            m.imp.T,
	}

	callEvent := &TimeProviderImpCall{
		newTicker: call,
	}

	m.imp.CallChan <- callEvent

	resp := <-responseChan

	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	return resp.Result0
}

// Now implements the interface method and records the call for testing.
// The method blocks until a response is injected via the test controller.
func (m *TimeProviderImpMock) Now() time.Time {
	responseChan := make(chan TimeProviderImpNowCallResponse, 1)

	call := &TimeProviderImpNowCall{
		responseChan: responseChan,
		t:            m.imp.T,
	}

	callEvent := &TimeProviderImpCall{
		now: call,
	}

	m.imp.CallChan <- callEvent

	resp := <-responseChan

	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	return resp.Result0
}

// TimeProviderImpNewTickerBuilder provides a fluent API for setting expectations on NewTicker calls.
// Use ExpectArgsAre for exact matching or ExpectArgsShould for matcher-based matching.
type TimeProviderImpNewTickerBuilder struct {
	imp     *TimeProviderImp
	timeout _time.Duration
}

// ExpectArgsAre waits for a NewTicker call with exactly the specified argument values.
// Returns the call object for response injection. Fails the test if the call
// doesn't arrive within the timeout or if arguments don't match exactly.
// Uses == for comparable types and reflect.DeepEqual for others.
func (bldr *TimeProviderImpNewTickerBuilder) ExpectArgsAre(d time.Duration) *TimeProviderImpNewTickerCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		if callToCheck.Name() != "NewTicker" {
			return false
		}
		methodCall := callToCheck.AsNewTicker()
		if !_reflect.DeepEqual(methodCall.d, d) {
			return false
		}
		return true
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	return call.AsNewTicker()
}

// ExpectArgsShould waits for a NewTicker call with arguments matching the given matchers.
// Use imptest.Any() to match any value, or imptest.Satisfies(fn) for custom matching.
// Returns the call object for response injection. Fails the test if the call
// doesn't arrive within the timeout or if any matcher fails.
func (bldr *TimeProviderImpNewTickerBuilder) ExpectArgsShould(d any) *TimeProviderImpNewTickerCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		if callToCheck.Name() != "NewTicker" {
			return false
		}
		methodCall := callToCheck.AsNewTicker()
		var ok bool
		ok, _ = _imptest.MatchValue(methodCall.d, d)
		if !ok {
			return false
		}
		return true
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	return call.AsNewTicker()
}

// InjectPanic waits for a NewTicker call and causes it to panic with the given value.
// This is a shortcut that combines waiting for the call with injecting a panic.
// Use this to test panic handling in code under test. Returns the call object for further operations.
func (bldr *TimeProviderImpNewTickerBuilder) InjectPanic(msg any) *TimeProviderImpNewTickerCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		return callToCheck.Name() == "NewTicker"
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	methodCall := call.AsNewTicker()
	methodCall.InjectPanic(msg)
	return methodCall
}

// InjectResult waits for a NewTicker call and immediately injects the return value.
// This is a shortcut that combines waiting for the call with injecting the result.
// Returns the call object for further operations. Fails if no call arrives within the timeout.
func (bldr *TimeProviderImpNewTickerBuilder) InjectResult(result syncengine.Ticker) *TimeProviderImpNewTickerCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		return callToCheck.Name() == "NewTicker"
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	methodCall := call.AsNewTicker()
	methodCall.InjectResult(result)
	return methodCall
}

// TimeProviderImpNewTickerCall represents a captured call to the NewTicker method.
// Use InjectResult to set the return value, or InjectPanic to cause the method to panic.
type TimeProviderImpNewTickerCall struct {
	responseChan chan TimeProviderImpNewTickerCallResponse
	done         bool
	d            time.Duration
	t            _imptest.Tester
}

// InjectPanic causes the mocked method to panic with the given value.
// Use this to test panic handling in code under test.
// The panic occurs in the goroutine where the mock was called.
func (c *TimeProviderImpNewTickerCall) InjectPanic(msg any) {
	c.done = true
	c.responseChan <- TimeProviderImpNewTickerCallResponse{Type: "panic", PanicValue: msg}
}

// InjectResult sets the return value for this method call and unblocks the caller.
// The mocked method will return the provided result value.
func (c *TimeProviderImpNewTickerCall) InjectResult(result syncengine.Ticker) {
	c.done = true
	c.responseChan <- TimeProviderImpNewTickerCallResponse{Type: "return", Result0: result}
}

// TimeProviderImpNewTickerCallResponse holds the response configuration for the NewTicker method.
// Set Type to "return" for normal returns, "panic" to cause a panic, or "resolve" for void methods.
type TimeProviderImpNewTickerCallResponse struct {
	Type       string // "return", "panic", or "resolve"
	Result0    syncengine.Ticker
	PanicValue any
}

// TimeProviderImpNowBuilder provides a fluent API for setting expectations on Now calls.
// Use ExpectArgsAre for exact matching or ExpectArgsShould for matcher-based matching.
type TimeProviderImpNowBuilder struct {
	imp     *TimeProviderImp
	timeout _time.Duration
}

// InjectPanic waits for a Now call and causes it to panic with the given value.
// This is a shortcut that combines waiting for the call with injecting a panic.
// Use this to test panic handling in code under test. Returns the call object for further operations.
func (bldr *TimeProviderImpNowBuilder) InjectPanic(msg any) *TimeProviderImpNowCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		return callToCheck.Name() == "Now"
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	methodCall := call.AsNow()
	methodCall.InjectPanic(msg)
	return methodCall
}

// InjectResult waits for a Now call and immediately injects the return value.
// This is a shortcut that combines waiting for the call with injecting the result.
// Returns the call object for further operations. Fails if no call arrives within the timeout.
func (bldr *TimeProviderImpNowBuilder) InjectResult(result time.Time) *TimeProviderImpNowCall {
	validator := func(callToCheck *TimeProviderImpCall) bool {
		return callToCheck.Name() == "Now"
	}

	call := bldr.imp.GetCall(bldr.timeout, validator)
	methodCall := call.AsNow()
	methodCall.InjectResult(result)
	return methodCall
}

// TimeProviderImpNowCall represents a captured call to the Now method.
// Use InjectResult to set the return value, or InjectPanic to cause the method to panic.
type TimeProviderImpNowCall struct {
	responseChan chan TimeProviderImpNowCallResponse
	done         bool
	t            _imptest.Tester
}

// InjectPanic causes the mocked method to panic with the given value.
// Use this to test panic handling in code under test.
// The panic occurs in the goroutine where the mock was called.
func (c *TimeProviderImpNowCall) InjectPanic(msg any) {
	c.done = true
	c.responseChan <- TimeProviderImpNowCallResponse{Type: "panic", PanicValue: msg}
}

// InjectResult sets the return value for this method call and unblocks the caller.
// The mocked method will return the provided result value.
func (c *TimeProviderImpNowCall) InjectResult(result time.Time) {
	c.done = true
	c.responseChan <- TimeProviderImpNowCallResponse{Type: "return", Result0: result}
}

// TimeProviderImpNowCallResponse holds the response configuration for the Now method.
// Set Type to "return" for normal returns, "panic" to cause a panic, or "resolve" for void methods.
type TimeProviderImpNowCallResponse struct {
	Type       string // "return", "panic", or "resolve"
	Result0    time.Time
	PanicValue any
}

// TimeProviderImpTimed provides timeout-configured expectation methods.
// Access via TimeProviderImp.Within(duration) to set a timeout for expectations.
type TimeProviderImpTimed struct {
	ExpectCallIs *TimeProviderImpExpectCallIs
}

// unexported variables.
var (
	// Compile-time verification that TimeProviderImpMock implements syncengine.TimeProvider.
	_ syncengine.TimeProvider = (*TimeProviderImpMock)(nil)
)
