// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	syncengine "github.com/joe/copy-files/internal/syncengine"
	"github.com/toejough/imptest/imptest"
	"testing"
)

// EngineGetStatus wraps a callable function for testing.
// Create with NewEngineGetStatus(t, yourFunction), call Start() to execute,
// then use ExpectReturnedValuesAre/Should() or ExpectPanicWith() to verify behavior.
type EngineGetStatus struct {
	*imptest.CallableController[EngineGetStatusReturn]
	callable func() *syncengine.Status
}

// NewEngineGetStatus creates a new wrapper for testing the callable function.
// Pass the function to test and a testing.TB to enable assertion failures.
//
// Example:
//
//	wrapper := NewEngineGetStatus(t, myFunction)
//	wrapper.Start(args...).ExpectReturnedValuesAre(expectedVals...)
func NewEngineGetStatus(t testing.TB, callable func() *syncengine.Status) *EngineGetStatus {
	return &EngineGetStatus{
		CallableController: imptest.NewCallableController[EngineGetStatusReturn](t),
		callable:           callable,
	}
}

// ExpectPanicWith asserts the callable panicked with a value matching the expectation.
// Use imptest.Any() to match any panic value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if the callable returned normally or panicked with a different value.
func (s *EngineGetStatus) ExpectPanicWith(expected any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Panicked != nil {
		ok, msg := imptest.MatchValue(s.Panicked, expected)
		if !ok {
			s.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnedValuesAre asserts the callable returned with exactly the specified values.
// Fails the test if the values don't match exactly or if the callable panicked.
// Uses == for comparison, so reference types must be the same instance.
func (s *EngineGetStatus) ExpectReturnedValuesAre(v1 *syncengine.Status) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		if s.Returned.Result0 != v1 {
			s.T.Fatalf("expected return value 0 to be %v, got %v", v1, s.Returned.Result0)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// ExpectReturnedValuesShould asserts return values match the given matchers.
// Use imptest.Any() to match any value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if any matcher fails or if the callable panicked.
func (s *EngineGetStatus) ExpectReturnedValuesShould(v1 any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		var ok bool
		var msg string
		ok, msg = imptest.MatchValue(s.Returned.Result0, v1)
		if !ok {
			s.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// Start begins execution of the callable in a goroutine with the provided arguments.
// Returns the wrapper for method chaining with expectation methods.
// Captures both normal returns and panics for verification.
//
// Example:
//
//	wrapper.Start(arg1, arg2).ExpectReturnedValuesAre(expectedResult)
func (s *EngineGetStatus) Start() *EngineGetStatus {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				s.PanicChan <- r
			}
		}()

		ret0 := s.callable()
		s.ReturnChan <- EngineGetStatusReturn{
			Result0: ret0,
		}
	}()
	return s
}

// EngineGetStatusResponse represents the response from the callable (either return or panic).
// Check EventType to determine if the callable returned normally or panicked.
// Access ReturnVal for return values or PanicVal for panic information.
type EngineGetStatusResponse struct {
	EventType string // "return" or "panic"
	ReturnVal *EngineGetStatusReturn
	PanicVal  any
}

// Type returns the event type: "return" for normal returns, "panic" for panics.
func (r *EngineGetStatusResponse) Type() string {
	return r.EventType
}

// EngineGetStatusReturn holds the return values from the callable function.
// Access individual return values via Result0, Result1, etc. fields.
type EngineGetStatusReturn struct {
	Result0 *syncengine.Status
}
