// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
)

// ResizablePoolMockHandle is the test handle for ResizablePool.
type ResizablePoolMockHandle struct {
	Mock       filesystem.ResizablePool
	Method     *ResizablePoolMockMethods
	Controller *_imptest.Imp
}

// ResizablePoolMockMethods holds method wrappers for setting expectations.
type ResizablePoolMockMethods struct {
	ResizePool     *ResizablePoolMockResizePoolMethod
	PoolSize       *_imptest.DependencyMethod
	PoolTargetSize *_imptest.DependencyMethod
	PoolMinSize    *_imptest.DependencyMethod
	PoolMaxSize    *_imptest.DependencyMethod
}

// ResizablePoolMockPoolMaxSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolMaxSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolMaxSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolMinSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolMinSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolMinSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolTargetSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolTargetSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolTargetSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockResizePoolArgs holds typed arguments for ResizePool.
type ResizablePoolMockResizePoolArgs struct {
	TargetSize int
}

// ResizablePoolMockResizePoolCall wraps DependencyCall with typed GetArgs.
type ResizablePoolMockResizePoolCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ResizablePoolMockResizePoolCall) GetArgs() ResizablePoolMockResizePoolArgs {
	raw := c.RawArgs()
	return ResizablePoolMockResizePoolArgs{
		TargetSize: raw[0].(int),
	}
}

// ResizablePoolMockResizePoolMethod wraps DependencyMethod with typed returns.
type ResizablePoolMockResizePoolMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ResizablePoolMockResizePoolMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ResizablePoolMockResizePoolMethod) ExpectCalledWithExactly(targetSize int) *ResizablePoolMockResizePoolCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(targetSize)
	return &ResizablePoolMockResizePoolCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ResizablePoolMockResizePoolMethod) ExpectCalledWithMatches(matchers ...any) *ResizablePoolMockResizePoolCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ResizablePoolMockResizePoolCall{DependencyCall: call}
}

// MockResizablePool creates a new ResizablePoolMockHandle for testing.
func MockResizablePool(t _imptest.TestReporter) *ResizablePoolMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &ResizablePoolMockMethods{
		ResizePool:     newResizablePoolMockResizePoolMethod(_imptest.NewDependencyMethod(ctrl, "ResizePool")),
		PoolSize:       _imptest.NewDependencyMethod(ctrl, "PoolSize"),
		PoolTargetSize: _imptest.NewDependencyMethod(ctrl, "PoolTargetSize"),
		PoolMinSize:    _imptest.NewDependencyMethod(ctrl, "PoolMinSize"),
		PoolMaxSize:    _imptest.NewDependencyMethod(ctrl, "PoolMaxSize"),
	}
	h := &ResizablePoolMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockResizablePoolImpl{handle: h}
	return h
}

// mockResizablePoolImpl implements filesystem.ResizablePool.
type mockResizablePoolImpl struct {
	handle *ResizablePoolMockHandle
}

// PoolMaxSize implements filesystem.ResizablePool.PoolMaxSize.
func (impl *mockResizablePoolImpl) PoolMaxSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolMaxSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolMinSize implements filesystem.ResizablePool.PoolMinSize.
func (impl *mockResizablePoolImpl) PoolMinSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolMinSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolSize implements filesystem.ResizablePool.PoolSize.
func (impl *mockResizablePoolImpl) PoolSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolTargetSize implements filesystem.ResizablePool.PoolTargetSize.
func (impl *mockResizablePoolImpl) PoolTargetSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolTargetSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// ResizePool implements filesystem.ResizablePool.ResizePool.
func (impl *mockResizablePoolImpl) ResizePool(targetSize int) {
	call := &_imptest.GenericCall{
		MethodName:   "ResizePool",
		Args:         []any{targetSize},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// newResizablePoolMockResizePoolMethod creates a typed method wrapper with Eventually initialized.
func newResizablePoolMockResizePoolMethod(dm *_imptest.DependencyMethod) *ResizablePoolMockResizePoolMethod {
	m := &ResizablePoolMockResizePoolMethod{DependencyMethod: dm}
	m.Eventually = &ResizablePoolMockResizePoolMethod{DependencyMethod: dm.Eventually}
	return m
}
