// Code generated by impgen. DO NOT EDIT.

package syncengine

import (
	_testing "testing"

	_imptest "github.com/toejough/imptest/imptest"
)

// EngineCancel wraps a callable function for testing.
// Create with NewEngineCancel(t, yourFunction), call Start() to execute,
// then use ExpectReturnedValuesAre/Should() or ExpectPanicWith() to verify behavior.
type EngineCancel struct {
	*_imptest.CallableController[struct{}]
	callable func()
}

// NewEngineCancel creates a new wrapper for testing the callable function.
// Pass the function to test and a testing.TB to enable assertion failures.
//
// Example:
//
//	wrapper := NewEngineCancel(t, myFunction)
//	wrapper.Start(args...).ExpectReturnedValuesAre(expectedVals...)
func NewEngineCancel(t _testing.TB, callable func()) *EngineCancel {
	return &EngineCancel{
		CallableController: _imptest.NewCallableController[struct{}](t),
		callable:           callable,
	}
}

// ExpectPanicWith asserts the callable panicked with a value matching the expectation.
// Use imptest.Any() to match any panic value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if the callable returned normally or panicked with a different value.
func (s *EngineCancel) ExpectPanicWith(expected any) {
	s.T.Helper()
	s.WaitForResponse()

	if s.Panicked != nil {
		ok, msg := _imptest.MatchValue(s.Panicked, expected)
		if !ok {
			s.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	s.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnedValuesAre asserts the callable returned with exactly the specified values.
// Fails the test if the values don't match exactly or if the callable panicked.
// Uses == for comparison, so reference types must be the same instance.
func (s *EngineCancel) ExpectReturnedValuesAre() {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// ExpectReturnedValuesShould asserts return values match the given matchers.
// Use imptest.Any() to match any value, or imptest.Satisfies(fn) for custom matching.
// Fails the test if any matcher fails or if the callable panicked.
func (s *EngineCancel) ExpectReturnedValuesShould() {
	s.T.Helper()
	s.WaitForResponse()

	if s.Returned != nil {
		return
	}

	s.T.Fatalf("expected function to return, but it panicked with: %v", s.Panicked)
}

// Start begins execution of the callable in a goroutine with the provided arguments.
// Returns the wrapper for method chaining with expectation methods.
// Captures both normal returns and panics for verification.
//
// Example:
//
//	wrapper.Start(arg1, arg2).ExpectReturnedValuesAre(expectedResult)
func (s *EngineCancel) Start() *EngineCancel {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				s.PanicChan <- r
			}
		}()

		s.callable()
		s.ReturnChan <- struct{}{}
	}()
	return s
}

// EngineCancelResponse represents the response from the callable (either return or panic).
// Check EventType to determine if the callable returned normally or panicked.
// Access ReturnVal for return values or PanicVal for panic information.
type EngineCancelResponse struct {
	EventType string // "return" or "panic"
	PanicVal  any
}

// Type returns the event type: "return" for normal returns, "panic" for panics.
func (r *EngineCancelResponse) Type() string {
	return r.EventType
}
