// Code generated by impgen. DO NOT EDIT.

package syncengine

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// WrapEngineCloseLogCallHandle represents a single call to the wrapped function.
type WrapEngineCloseLogCallHandle struct {
	*_imptest.CallableController[WrapEngineCloseLogReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapEngineCloseLogCallHandleEventually
}

// ExpectCompletes verifies the function completes without panicking.
func (h *WrapEngineCloseLogCallHandle) ExpectCompletes() {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		h.T.Fatalf("expected function to complete, but it panicked with: %v", h.Panicked)
	}
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapEngineCloseLogCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapEngineCloseLogCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// WrapEngineCloseLogCallHandleEventually wraps a call handle for async expectation registration.
type WrapEngineCloseLogCallHandleEventually struct {
	h *WrapEngineCloseLogCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapEngineCloseLogCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapEngineCloseLogCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapEngineCloseLogCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapEngineCloseLogReturnsReturn holds the return values from the wrapped function.
type WrapEngineCloseLogReturnsReturn struct {
}

// WrapEngineCloseLogWrapperHandle is the test handle for a wrapped function.
type WrapEngineCloseLogWrapperHandle struct {
	Method     *WrapEngineCloseLogWrapperMethod
	Controller *_imptest.TargetController
}

// WrapEngineCloseLogWrapperMethod wraps a function for testing.
type WrapEngineCloseLogWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func()
}

// Start executes the wrapped function in a goroutine.
func (m *WrapEngineCloseLogWrapperMethod) Start() *WrapEngineCloseLogCallHandle {
	handle := &WrapEngineCloseLogCallHandle{
		CallableController: _imptest.NewCallableController[WrapEngineCloseLogReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapEngineCloseLogCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		m.callable()
		handle.ReturnChan <- WrapEngineCloseLogReturnsReturn{}
	}()
	return handle
}

// WrapEngineCloseLog wraps a function for testing.
func WrapEngineCloseLog(t _imptest.TestReporter, fn func()) *WrapEngineCloseLogWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapEngineCloseLogWrapperHandle{
		Method: &WrapEngineCloseLogWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
