// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
)

// ResizablePoolMock is the mock for ResizablePool.
type ResizablePoolMock struct {
	imp            *_imptest.Imp
	ResizePool     *ResizablePoolMockResizePoolMethod
	PoolSize       *_imptest.DependencyMethod
	PoolTargetSize *_imptest.DependencyMethod
	PoolMinSize    *_imptest.DependencyMethod
	PoolMaxSize    *_imptest.DependencyMethod
}

// Interface returns the ResizablePool implementation that can be passed to code under test.
func (m *ResizablePoolMock) Interface() filesystem.ResizablePool {
	return &mockResizablePoolImpl{mock: m}
}

// ResizablePoolMockPoolMaxSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolMaxSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolMaxSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolMinSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolMinSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolMinSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockPoolTargetSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ResizablePoolMockPoolTargetSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ResizablePoolMockPoolTargetSizeCall) InjectReturnValues(result0 int) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ResizablePoolMockResizePoolArgs holds typed arguments for ResizePool.
type ResizablePoolMockResizePoolArgs struct {
	TargetSize int
}

// ResizablePoolMockResizePoolCall wraps DependencyCall with typed GetArgs.
type ResizablePoolMockResizePoolCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ResizablePoolMockResizePoolCall) GetArgs() ResizablePoolMockResizePoolArgs {
	raw := c.RawArgs()
	return ResizablePoolMockResizePoolArgs{
		TargetSize: raw[0].(int),
	}
}

// ResizablePoolMockResizePoolMethod wraps DependencyMethod with typed returns.
type ResizablePoolMockResizePoolMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *ResizablePoolMockResizePoolMethod) Eventually() *ResizablePoolMockResizePoolMethod {
	return &ResizablePoolMockResizePoolMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ResizablePoolMockResizePoolMethod) ExpectCalledWithExactly(targetSize int) *ResizablePoolMockResizePoolCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(targetSize)
	return &ResizablePoolMockResizePoolCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ResizablePoolMockResizePoolMethod) ExpectCalledWithMatches(matchers ...any) *ResizablePoolMockResizePoolCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ResizablePoolMockResizePoolCall{DependencyCall: call}
}

// MockResizablePool creates a new ResizablePoolMock for testing.
func MockResizablePool(t _imptest.TestReporter) *ResizablePoolMock {
	imp := _imptest.NewImp(t)
	return &ResizablePoolMock{
		imp:            imp,
		ResizePool:     &ResizablePoolMockResizePoolMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "ResizePool")},
		PoolSize:       _imptest.NewDependencyMethod(imp, "PoolSize"),
		PoolTargetSize: _imptest.NewDependencyMethod(imp, "PoolTargetSize"),
		PoolMinSize:    _imptest.NewDependencyMethod(imp, "PoolMinSize"),
		PoolMaxSize:    _imptest.NewDependencyMethod(imp, "PoolMaxSize"),
	}
}

// mockResizablePoolImpl implements filesystem.ResizablePool.
type mockResizablePoolImpl struct {
	mock *ResizablePoolMock
}

// PoolMaxSize implements filesystem.ResizablePool.PoolMaxSize.
func (impl *mockResizablePoolImpl) PoolMaxSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolMaxSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolMinSize implements filesystem.ResizablePool.PoolMinSize.
func (impl *mockResizablePoolImpl) PoolMinSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolMinSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolSize implements filesystem.ResizablePool.PoolSize.
func (impl *mockResizablePoolImpl) PoolSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// PoolTargetSize implements filesystem.ResizablePool.PoolTargetSize.
func (impl *mockResizablePoolImpl) PoolTargetSize() int {
	call := &_imptest.GenericCall{
		MethodName:   "PoolTargetSize",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	return result1
}

// ResizePool implements filesystem.ResizablePool.ResizePool.
func (impl *mockResizablePoolImpl) ResizePool(targetSize int) {
	call := &_imptest.GenericCall{
		MethodName:   "ResizePool",
		Args:         []any{targetSize},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}
