// Code generated by impgen. DO NOT EDIT.

package syncengine_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
)

// FileScannerMock is the mock for FileScanner.
type FileScannerMock struct {
	imp  *_imptest.Imp
	Next *_imptest.DependencyMethod
	Err  *_imptest.DependencyMethod
}

// Interface returns the FileScanner implementation that can be passed to code under test.
func (m *FileScannerMock) Interface() filesystem.FileScanner {
	return &mockFileScannerImpl{mock: m}
}

// FileScannerMockErrCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileScannerMockErrCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileScannerMockErrCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileScannerMockNextCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileScannerMockNextCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileScannerMockNextCall) InjectReturnValues(result0 filesystem.FileInfo, result1 bool) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// MockFileScanner creates a new FileScannerMock for testing.
func MockFileScanner(t _imptest.TestReporter) *FileScannerMock {
	imp := _imptest.NewImp(t)
	return &FileScannerMock{
		imp:  imp,
		Next: _imptest.NewDependencyMethod(imp, "Next"),
		Err:  _imptest.NewDependencyMethod(imp, "Err"),
	}
}

// mockFileScannerImpl implements filesystem.FileScanner.
type mockFileScannerImpl struct {
	mock *FileScannerMock
}

// Err implements filesystem.FileScanner.Err.
func (impl *mockFileScannerImpl) Err() error {
	call := &_imptest.GenericCall{
		MethodName:   "Err",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// Next implements filesystem.FileScanner.Next.
func (impl *mockFileScannerImpl) Next() (filesystem.FileInfo, bool) {
	call := &_imptest.GenericCall{
		MethodName:   "Next",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 filesystem.FileInfo
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(filesystem.FileInfo); ok {
			result1 = value
		}
	}

	var result2 bool
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(bool); ok {
			result2 = value
		}
	}

	return result1, result2
}
