// Code generated by impgen. DO NOT EDIT.

package fileops_test

import (
	fileops "github.com/joe/copy-files/pkg/fileops"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapCountFilesWithProgressReturnsReturn holds the return values from the wrapped function.
type WrapCountFilesWithProgressReturnsReturn struct {
	Result0 int
	Result1 error
}

// WrapCountFilesWithProgressWrapper wraps a function for testing.
type WrapCountFilesWithProgressWrapper struct {
	*_imptest.CallableController[WrapCountFilesWithProgressReturnsReturn]
	callable func(string, fileops.CountProgressCallback) (int, error)
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapCountFilesWithProgressWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapCountFilesWithProgressWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapCountFilesWithProgressWrapper) ExpectReturnsEqual(v0 int, v1 error) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		if !_reflect.DeepEqual(w.Returned.Result1, v1) {
			w.T.Fatalf("expected return value 1 to be %v, got %v", v1, w.Returned.Result1)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapCountFilesWithProgressWrapper) ExpectReturnsMatch(v0 any, v1 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(w.Returned.Result1, v1)
		if !ok {
			w.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapCountFilesWithProgressWrapper) Start(rootPath string, progressCallback fileops.CountProgressCallback) *WrapCountFilesWithProgressWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0, ret1 := w.callable(rootPath, progressCallback)
		w.ReturnChan <- WrapCountFilesWithProgressReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return w
}

// WrapCountFilesWithProgress wraps a function for testing.
func WrapCountFilesWithProgress(t _imptest.TestReporter, fn func(string, fileops.CountProgressCallback) (int, error)) *WrapCountFilesWithProgressWrapper {
	return &WrapCountFilesWithProgressWrapper{
		CallableController: _imptest.NewCallableController[WrapCountFilesWithProgressReturnsReturn](t),
		callable:           fn,
	}
}
