// Code generated by impgen. DO NOT EDIT.

package fileops_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapCompareFilesBytesCallHandle represents a single call to the wrapped function.
type WrapCompareFilesBytesCallHandle struct {
	*_imptest.CallableController[WrapCompareFilesBytesReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapCompareFilesBytesCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapCompareFilesBytesCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapCompareFilesBytesCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapCompareFilesBytesCallHandle) ExpectReturnsEqual(v0 bool, v1 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		if !_reflect.DeepEqual(h.Returned.Result1, v1) {
			h.T.Fatalf("expected return value 1 to be %v, got %v", v1, h.Returned.Result1)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapCompareFilesBytesCallHandle) ExpectReturnsMatch(v0 any, v1 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result1, v1)
		if !ok {
			h.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapCompareFilesBytesCallHandleEventually wraps a call handle for async expectation registration.
type WrapCompareFilesBytesCallHandleEventually struct {
	h *WrapCompareFilesBytesCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapCompareFilesBytesCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapCompareFilesBytesCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapCompareFilesBytesCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapCompareFilesBytesReturnsReturn holds the return values from the wrapped function.
type WrapCompareFilesBytesReturnsReturn struct {
	Result0 bool
	Result1 error
}

// WrapCompareFilesBytesWrapperHandle is the test handle for a wrapped function.
type WrapCompareFilesBytesWrapperHandle struct {
	Method     *WrapCompareFilesBytesWrapperMethod
	Controller *_imptest.TargetController
}

// WrapCompareFilesBytesWrapperMethod wraps a function for testing.
type WrapCompareFilesBytesWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(string, string) (bool, error)
}

// Start executes the wrapped function in a goroutine.
func (m *WrapCompareFilesBytesWrapperMethod) Start(path1 string, path2 string) *WrapCompareFilesBytesCallHandle {
	handle := &WrapCompareFilesBytesCallHandle{
		CallableController: _imptest.NewCallableController[WrapCompareFilesBytesReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapCompareFilesBytesCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0, ret1 := m.callable(path1, path2)
		handle.ReturnChan <- WrapCompareFilesBytesReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return handle
}

// WrapCompareFilesBytes wraps a function for testing.
func WrapCompareFilesBytes(t _imptest.TestReporter, fn func(string, string) (bool, error)) *WrapCompareFilesBytesWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapCompareFilesBytesWrapperHandle{
		Method: &WrapCompareFilesBytesWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
