// Code generated by impgen. DO NOT EDIT.

package fileops_test

import (
	fileops "github.com/joe/copy-files/pkg/fileops"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapCopyFileReturnsReturn holds the return values from the wrapped function.
type WrapCopyFileReturnsReturn struct {
	Result0 int64
	Result1 error
}

// WrapCopyFileWrapper wraps a function for testing.
type WrapCopyFileWrapper struct {
	*_imptest.CallableController[WrapCopyFileReturnsReturn]
	callable func(string, string, fileops.ProgressCallback) (int64, error)
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapCopyFileWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapCopyFileWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapCopyFileWrapper) ExpectReturnsEqual(v0 int64, v1 error) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		if !_reflect.DeepEqual(w.Returned.Result1, v1) {
			w.T.Fatalf("expected return value 1 to be %v, got %v", v1, w.Returned.Result1)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapCopyFileWrapper) ExpectReturnsMatch(v0 any, v1 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(w.Returned.Result1, v1)
		if !ok {
			w.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapCopyFileWrapper) Start(src string, dst string, progress fileops.ProgressCallback) *WrapCopyFileWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0, ret1 := w.callable(src, dst, progress)
		w.ReturnChan <- WrapCopyFileReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return w
}

// WrapCopyFile wraps a function for testing.
func WrapCopyFile(t _imptest.TestReporter, fn func(string, string, fileops.ProgressCallback) (int64, error)) *WrapCopyFileWrapper {
	return &WrapCopyFileWrapper{
		CallableController: _imptest.NewCallableController[WrapCopyFileReturnsReturn](t),
		callable:           fn,
	}
}
