// Code generated by impgen. DO NOT EDIT.

package fileops_test

import (
	fileops "github.com/joe/copy-files/pkg/fileops"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapFilesNeedSyncReturnsReturn holds the return values from the wrapped function.
type WrapFilesNeedSyncReturnsReturn struct {
	Result0 bool
}

// WrapFilesNeedSyncWrapper wraps a function for testing.
type WrapFilesNeedSyncWrapper struct {
	*_imptest.CallableController[WrapFilesNeedSyncReturnsReturn]
	callable func(*fileops.FileInfo, *fileops.FileInfo) bool
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (w *WrapFilesNeedSyncWrapper) ExpectPanicEquals(expected any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, expected)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (w *WrapFilesNeedSyncWrapper) ExpectPanicMatches(matcher any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Panicked != nil {
		ok, msg := _imptest.MatchValue(w.Panicked, matcher)
		if !ok {
			w.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (w *WrapFilesNeedSyncWrapper) ExpectReturnsEqual(v0 bool) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		if !_reflect.DeepEqual(w.Returned.Result0, v0) {
			w.T.Fatalf("expected return value 0 to be %v, got %v", v0, w.Returned.Result0)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (w *WrapFilesNeedSyncWrapper) ExpectReturnsMatch(v0 any) {
	w.T.Helper()
	w.WaitForResponse()

	if w.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(w.Returned.Result0, v0)
		if !ok {
			w.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	w.T.Fatalf("expected function to return, but it panicked with: %v", w.Panicked)
}

// Start executes the wrapped function in a goroutine.
func (w *WrapFilesNeedSyncWrapper) Start(src *fileops.FileInfo, dst *fileops.FileInfo) *WrapFilesNeedSyncWrapper {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				w.PanicChan <- r
			}
		}()
		ret0 := w.callable(src, dst)
		w.ReturnChan <- WrapFilesNeedSyncReturnsReturn{Result0: ret0}
	}()
	return w
}

// WrapFilesNeedSync wraps a function for testing.
func WrapFilesNeedSync(t _imptest.TestReporter, fn func(*fileops.FileInfo, *fileops.FileInfo) bool) *WrapFilesNeedSyncWrapper {
	return &WrapFilesNeedSyncWrapper{
		CallableController: _imptest.NewCallableController[WrapFilesNeedSyncReturnsReturn](t),
		callable:           fn,
	}
}
