// Code generated by impgen. DO NOT EDIT.

package fileops_test

import (
	fileops "github.com/joe/copy-files/pkg/fileops"
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapFilesNeedSyncCallHandle represents a single call to the wrapped function.
type WrapFilesNeedSyncCallHandle struct {
	*_imptest.CallableController[WrapFilesNeedSyncReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapFilesNeedSyncCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapFilesNeedSyncCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapFilesNeedSyncCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapFilesNeedSyncCallHandle) ExpectReturnsEqual(v0 bool) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapFilesNeedSyncCallHandle) ExpectReturnsMatch(v0 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapFilesNeedSyncCallHandleEventually wraps a call handle for async expectation registration.
type WrapFilesNeedSyncCallHandleEventually struct {
	h *WrapFilesNeedSyncCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapFilesNeedSyncCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapFilesNeedSyncCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapFilesNeedSyncCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapFilesNeedSyncReturnsReturn holds the return values from the wrapped function.
type WrapFilesNeedSyncReturnsReturn struct {
	Result0 bool
}

// WrapFilesNeedSyncWrapperHandle is the test handle for a wrapped function.
type WrapFilesNeedSyncWrapperHandle struct {
	Method     *WrapFilesNeedSyncWrapperMethod
	Controller *_imptest.TargetController
}

// WrapFilesNeedSyncWrapperMethod wraps a function for testing.
type WrapFilesNeedSyncWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(*fileops.FileInfo, *fileops.FileInfo) bool
}

// Start executes the wrapped function in a goroutine.
func (m *WrapFilesNeedSyncWrapperMethod) Start(src *fileops.FileInfo, dst *fileops.FileInfo) *WrapFilesNeedSyncCallHandle {
	handle := &WrapFilesNeedSyncCallHandle{
		CallableController: _imptest.NewCallableController[WrapFilesNeedSyncReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapFilesNeedSyncCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0 := m.callable(src, dst)
		handle.ReturnChan <- WrapFilesNeedSyncReturnsReturn{Result0: ret0}
	}()
	return handle
}

// WrapFilesNeedSync wraps a function for testing.
func WrapFilesNeedSync(t _imptest.TestReporter, fn func(*fileops.FileInfo, *fileops.FileInfo) bool) *WrapFilesNeedSyncWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapFilesNeedSyncWrapperHandle{
		Method: &WrapFilesNeedSyncWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
