// Code generated by impgen. DO NOT EDIT.

package filesystem

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// SSHClientCloserMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SSHClientCloserMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SSHClientCloserMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SSHClientCloserMockHandle is the test handle for SSHClientCloser.
type SSHClientCloserMockHandle struct {
	Mock       SSHClientCloser
	Method     *SSHClientCloserMockMethods
	Controller *_imptest.Imp
}

// SSHClientCloserMockMethods holds method wrappers for setting expectations.
type SSHClientCloserMockMethods struct {
	Close *_imptest.DependencyMethod
}

// MockSSHClientCloser creates a new SSHClientCloserMockHandle for testing.
func MockSSHClientCloser(t _imptest.TestReporter) *SSHClientCloserMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &SSHClientCloserMockMethods{
		Close: _imptest.NewDependencyMethod(ctrl, "Close"),
	}
	h := &SSHClientCloserMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockSSHClientCloserImpl{handle: h}
	return h
}

// mockSSHClientCloserImpl implements SSHClientCloser.
type mockSSHClientCloserImpl struct {
	handle *SSHClientCloserMockHandle
}

// Close implements SSHClientCloser.Close.
func (impl *mockSSHClientCloserImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
