// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	sftp "github.com/pkg/sftp"
	_imptest "github.com/toejough/imptest/imptest"
)

// ClientPoolMockAcquireCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ClientPoolMockAcquireCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ClientPoolMockAcquireCall) InjectReturnValues(result0 *sftp.Client, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// ClientPoolMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type ClientPoolMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *ClientPoolMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// ClientPoolMockHandle is the test handle for ClientPool.
type ClientPoolMockHandle struct {
	Mock       filesystem.ClientPool
	Method     *ClientPoolMockMethods
	Controller *_imptest.Imp
}

// ClientPoolMockMethods holds method wrappers for setting expectations.
type ClientPoolMockMethods struct {
	Acquire *_imptest.DependencyMethod
	Release *ClientPoolMockReleaseMethod
	Close   *_imptest.DependencyMethod
}

// ClientPoolMockReleaseArgs holds typed arguments for Release.
type ClientPoolMockReleaseArgs struct {
	Client *sftp.Client
}

// ClientPoolMockReleaseCall wraps DependencyCall with typed GetArgs.
type ClientPoolMockReleaseCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *ClientPoolMockReleaseCall) GetArgs() ClientPoolMockReleaseArgs {
	raw := c.RawArgs()
	return ClientPoolMockReleaseArgs{
		Client: raw[0].(*sftp.Client),
	}
}

// ClientPoolMockReleaseMethod wraps DependencyMethod with typed returns.
type ClientPoolMockReleaseMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *ClientPoolMockReleaseMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *ClientPoolMockReleaseMethod) ExpectCalledWithExactly(client *sftp.Client) *ClientPoolMockReleaseCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(client)
	return &ClientPoolMockReleaseCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *ClientPoolMockReleaseMethod) ExpectCalledWithMatches(matchers ...any) *ClientPoolMockReleaseCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &ClientPoolMockReleaseCall{DependencyCall: call}
}

// MockClientPool creates a new ClientPoolMockHandle for testing.
func MockClientPool(t _imptest.TestReporter) *ClientPoolMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &ClientPoolMockMethods{
		Acquire: _imptest.NewDependencyMethod(ctrl, "Acquire"),
		Release: newClientPoolMockReleaseMethod(_imptest.NewDependencyMethod(ctrl, "Release")),
		Close:   _imptest.NewDependencyMethod(ctrl, "Close"),
	}
	h := &ClientPoolMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockClientPoolImpl{handle: h}
	return h
}

// mockClientPoolImpl implements filesystem.ClientPool.
type mockClientPoolImpl struct {
	handle *ClientPoolMockHandle
}

// Acquire implements filesystem.ClientPool.Acquire.
func (impl *mockClientPoolImpl) Acquire() (*sftp.Client, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Acquire",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 *sftp.Client
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(*sftp.Client); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Close implements filesystem.ClientPool.Close.
func (impl *mockClientPoolImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// Release implements filesystem.ClientPool.Release.
func (impl *mockClientPoolImpl) Release(client *sftp.Client) {
	call := &_imptest.GenericCall{
		MethodName:   "Release",
		Args:         []any{client},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

}

// newClientPoolMockReleaseMethod creates a typed method wrapper with Eventually initialized.
func newClientPoolMockReleaseMethod(dm *_imptest.DependencyMethod) *ClientPoolMockReleaseMethod {
	m := &ClientPoolMockReleaseMethod{DependencyMethod: dm}
	m.Eventually = &ClientPoolMockReleaseMethod{DependencyMethod: dm.Eventually}
	return m
}
