// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
	ssh "golang.org/x/crypto/ssh"
)

// SSHDialerMockDialArgs holds typed arguments for Dial.
type SSHDialerMockDialArgs struct {
	Network string
	Addr    string
	Config  *ssh.ClientConfig
}

// SSHDialerMockDialCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SSHDialerMockDialCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SSHDialerMockDialCall) GetArgs() SSHDialerMockDialArgs {
	raw := c.RawArgs()
	return SSHDialerMockDialArgs{
		Network: raw[0].(string),
		Addr:    raw[1].(string),
		Config:  raw[2].(*ssh.ClientConfig),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SSHDialerMockDialCall) InjectReturnValues(result0 *ssh.Client, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// SSHDialerMockDialMethod wraps DependencyMethod with typed returns.
type SSHDialerMockDialMethod struct {
	*_imptest.DependencyMethod
	// Eventually is the async version of this method for concurrent code.
	Eventually *SSHDialerMockDialMethod
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SSHDialerMockDialMethod) ExpectCalledWithExactly(network string, addr string, config *ssh.ClientConfig) *SSHDialerMockDialCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(network, addr, config)
	return &SSHDialerMockDialCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SSHDialerMockDialMethod) ExpectCalledWithMatches(matchers ...any) *SSHDialerMockDialCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SSHDialerMockDialCall{DependencyCall: call}
}

// SSHDialerMockHandle is the test handle for SSHDialer.
type SSHDialerMockHandle struct {
	Mock       filesystem.SSHDialer
	Method     *SSHDialerMockMethods
	Controller *_imptest.Imp
}

// SSHDialerMockMethods holds method wrappers for setting expectations.
type SSHDialerMockMethods struct {
	Dial *SSHDialerMockDialMethod
}

// MockSSHDialer creates a new SSHDialerMockHandle for testing.
func MockSSHDialer(t _imptest.TestReporter) *SSHDialerMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &SSHDialerMockMethods{
		Dial: newSSHDialerMockDialMethod(_imptest.NewDependencyMethod(ctrl, "Dial")),
	}
	h := &SSHDialerMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockSSHDialerImpl{handle: h}
	return h
}

// mockSSHDialerImpl implements filesystem.SSHDialer.
type mockSSHDialerImpl struct {
	handle *SSHDialerMockHandle
}

// Dial implements filesystem.SSHDialer.Dial.
func (impl *mockSSHDialerImpl) Dial(network string, addr string, config *ssh.ClientConfig) (*ssh.Client, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Dial",
		Args:         []any{network, addr, config},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 *ssh.Client
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(*ssh.Client); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// newSSHDialerMockDialMethod creates a typed method wrapper with Eventually initialized.
func newSSHDialerMockDialMethod(dm *_imptest.DependencyMethod) *SSHDialerMockDialMethod {
	m := &SSHDialerMockDialMethod{DependencyMethod: dm}
	m.Eventually = &SSHDialerMockDialMethod{DependencyMethod: dm.Eventually}
	return m
}
