// Code generated by impgen. DO NOT EDIT.

package filesystem

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// SSHClientCloserMock is the mock for SSHClientCloser.
type SSHClientCloserMock struct {
	imp   *_imptest.Imp
	Close *_imptest.DependencyMethod
}

// Interface returns the SSHClientCloser implementation that can be passed to code under test.
func (m *SSHClientCloserMock) Interface() SSHClientCloser {
	return &mockSSHClientCloserImpl{mock: m}
}

// SSHClientCloserMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SSHClientCloserMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SSHClientCloserMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockSSHClientCloser creates a new SSHClientCloserMock for testing.
func MockSSHClientCloser(t _imptest.TestReporter) *SSHClientCloserMock {
	imp := _imptest.NewImp(t)
	return &SSHClientCloserMock{
		imp:   imp,
		Close: _imptest.NewDependencyMethod(imp, "Close"),
	}
}

// mockSSHClientCloserImpl implements SSHClientCloser.
type mockSSHClientCloserImpl struct {
	mock *SSHClientCloserMock
}

// Close implements SSHClientCloser.Close.
func (impl *mockSSHClientCloserImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
