// Code generated by impgen. DO NOT EDIT.

package filesystem

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// SFTPClientCloserMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SFTPClientCloserMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SFTPClientCloserMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SFTPClientCloserMockHandle is the test handle for SFTPClientCloser.
type SFTPClientCloserMockHandle struct {
	Mock       SFTPClientCloser
	Method     *SFTPClientCloserMockMethods
	Controller *_imptest.Imp
}

// SFTPClientCloserMockMethods holds method wrappers for setting expectations.
type SFTPClientCloserMockMethods struct {
	Close *_imptest.DependencyMethod
}

// MockSFTPClientCloser creates a new SFTPClientCloserMockHandle for testing.
func MockSFTPClientCloser(t _imptest.TestReporter) *SFTPClientCloserMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &SFTPClientCloserMockMethods{
		Close: _imptest.NewDependencyMethod(ctrl, "Close"),
	}
	h := &SFTPClientCloserMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockSFTPClientCloserImpl{handle: h}
	return h
}

// mockSFTPClientCloserImpl implements SFTPClientCloser.
type mockSFTPClientCloserImpl struct {
	handle *SFTPClientCloserMockHandle
}

// Close implements SFTPClientCloser.Close.
func (impl *mockSFTPClientCloserImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
