// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
	os "os"
)

// SftpFileMock is the mock for SftpFile.
type SftpFileMock struct {
	imp   *_imptest.Imp
	Read  *SftpFileMockReadMethod
	Write *SftpFileMockWriteMethod
	Close *_imptest.DependencyMethod
	Stat  *_imptest.DependencyMethod
}

// Interface returns the SftpFile implementation that can be passed to code under test.
func (m *SftpFileMock) Interface() filesystem.SftpFile {
	return &mockSftpFileImpl{mock: m}
}

// SftpFileMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SftpFileMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SftpFileMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// SftpFileMockReadArgs holds typed arguments for Read.
type SftpFileMockReadArgs struct {
	P []byte
}

// SftpFileMockReadCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SftpFileMockReadCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SftpFileMockReadCall) GetArgs() SftpFileMockReadArgs {
	raw := c.RawArgs()
	return SftpFileMockReadArgs{
		P: raw[0].([]byte),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SftpFileMockReadCall) InjectReturnValues(result0 int, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// SftpFileMockReadMethod wraps DependencyMethod with typed returns.
type SftpFileMockReadMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *SftpFileMockReadMethod) Eventually() *SftpFileMockReadMethod {
	return &SftpFileMockReadMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SftpFileMockReadMethod) ExpectCalledWithExactly(p []byte) *SftpFileMockReadCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(p)
	return &SftpFileMockReadCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SftpFileMockReadMethod) ExpectCalledWithMatches(matchers ...any) *SftpFileMockReadCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SftpFileMockReadCall{DependencyCall: call}
}

// SftpFileMockStatCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SftpFileMockStatCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SftpFileMockStatCall) InjectReturnValues(result0 os.FileInfo, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// SftpFileMockWriteArgs holds typed arguments for Write.
type SftpFileMockWriteArgs struct {
	P []byte
}

// SftpFileMockWriteCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SftpFileMockWriteCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SftpFileMockWriteCall) GetArgs() SftpFileMockWriteArgs {
	raw := c.RawArgs()
	return SftpFileMockWriteArgs{
		P: raw[0].([]byte),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SftpFileMockWriteCall) InjectReturnValues(result0 int, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// SftpFileMockWriteMethod wraps DependencyMethod with typed returns.
type SftpFileMockWriteMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *SftpFileMockWriteMethod) Eventually() *SftpFileMockWriteMethod {
	return &SftpFileMockWriteMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SftpFileMockWriteMethod) ExpectCalledWithExactly(p []byte) *SftpFileMockWriteCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(p)
	return &SftpFileMockWriteCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SftpFileMockWriteMethod) ExpectCalledWithMatches(matchers ...any) *SftpFileMockWriteCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SftpFileMockWriteCall{DependencyCall: call}
}

// MockSftpFile creates a new SftpFileMock for testing.
func MockSftpFile(t _imptest.TestReporter) *SftpFileMock {
	imp := _imptest.NewImp(t)
	return &SftpFileMock{
		imp:   imp,
		Read:  &SftpFileMockReadMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Read")},
		Write: &SftpFileMockWriteMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Write")},
		Close: _imptest.NewDependencyMethod(imp, "Close"),
		Stat:  _imptest.NewDependencyMethod(imp, "Stat"),
	}
}

// mockSftpFileImpl implements filesystem.SftpFile.
type mockSftpFileImpl struct {
	mock *SftpFileMock
}

// Close implements filesystem.SftpFile.Close.
func (impl *mockSftpFileImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// Read implements filesystem.SftpFile.Read.
func (impl *mockSftpFileImpl) Read(p []byte) (int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Read",
		Args:         []any{p},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Stat implements filesystem.SftpFile.Stat.
func (impl *mockSftpFileImpl) Stat() (os.FileInfo, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Stat",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 os.FileInfo
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(os.FileInfo); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}

// Write implements filesystem.SftpFile.Write.
func (impl *mockSftpFileImpl) Write(p []byte) (int, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Write",
		Args:         []any{p},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}
