// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
	ssh "golang.org/x/crypto/ssh"
)

// SSHDialerMock is the mock for SSHDialer.
type SSHDialerMock struct {
	imp  *_imptest.Imp
	Dial *SSHDialerMockDialMethod
}

// Interface returns the SSHDialer implementation that can be passed to code under test.
func (m *SSHDialerMock) Interface() filesystem.SSHDialer {
	return &mockSSHDialerImpl{mock: m}
}

// SSHDialerMockDialArgs holds typed arguments for Dial.
type SSHDialerMockDialArgs struct {
	Network string
	Addr    string
	Config  *ssh.ClientConfig
}

// SSHDialerMockDialCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SSHDialerMockDialCall struct {
	*_imptest.DependencyCall
}

// GetArgs returns the typed arguments for this call.
func (c *SSHDialerMockDialCall) GetArgs() SSHDialerMockDialArgs {
	raw := c.RawArgs()
	return SSHDialerMockDialArgs{
		Network: raw[0].(string),
		Addr:    raw[1].(string),
		Config:  raw[2].(*ssh.ClientConfig),
	}
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SSHDialerMockDialCall) InjectReturnValues(result0 *ssh.Client, result1 error) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// SSHDialerMockDialMethod wraps DependencyMethod with typed returns.
type SSHDialerMockDialMethod struct {
	*_imptest.DependencyMethod
}

// Eventually switches to unordered mode for concurrent code.
// Waits indefinitely for a matching call; mismatches are queued.
// Returns typed wrapper preserving type-safe GetArgs() access.
func (m *SSHDialerMockDialMethod) Eventually() *SSHDialerMockDialMethod {
	return &SSHDialerMockDialMethod{DependencyMethod: m.DependencyMethod.Eventually()}
}

// ExpectCalledWithExactly waits for a call with exactly the specified arguments.
func (m *SSHDialerMockDialMethod) ExpectCalledWithExactly(network string, addr string, config *ssh.ClientConfig) *SSHDialerMockDialCall {
	call := m.DependencyMethod.ExpectCalledWithExactly(network, addr, config)
	return &SSHDialerMockDialCall{DependencyCall: call}
}

// ExpectCalledWithMatches waits for a call with arguments matching the given matchers.
func (m *SSHDialerMockDialMethod) ExpectCalledWithMatches(matchers ...any) *SSHDialerMockDialCall {
	call := m.DependencyMethod.ExpectCalledWithMatches(matchers...)
	return &SSHDialerMockDialCall{DependencyCall: call}
}

// MockSSHDialer creates a new SSHDialerMock for testing.
func MockSSHDialer(t _imptest.TestReporter) *SSHDialerMock {
	imp := _imptest.NewImp(t)
	return &SSHDialerMock{
		imp:  imp,
		Dial: &SSHDialerMockDialMethod{DependencyMethod: _imptest.NewDependencyMethod(imp, "Dial")},
	}
}

// mockSSHDialerImpl implements filesystem.SSHDialer.
type mockSSHDialerImpl struct {
	mock *SSHDialerMock
}

// Dial implements filesystem.SSHDialer.Dial.
func (impl *mockSSHDialerImpl) Dial(network string, addr string, config *ssh.ClientConfig) (*ssh.Client, error) {
	call := &_imptest.GenericCall{
		MethodName:   "Dial",
		Args:         []any{network, addr, config},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 *ssh.Client
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(*ssh.Client); ok {
			result1 = value
		}
	}

	var result2 error
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(error); ok {
			result2 = value
		}
	}

	return result1, result2
}
