// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	filesystem "github.com/joe/copy-files/pkg/filesystem"
	_imptest "github.com/toejough/imptest/imptest"
)

// FileScannerMockErrCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileScannerMockErrCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileScannerMockErrCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileScannerMockHandle is the test handle for FileScanner.
type FileScannerMockHandle struct {
	Mock       filesystem.FileScanner
	Method     *FileScannerMockMethods
	Controller *_imptest.Imp
}

// FileScannerMockMethods holds method wrappers for setting expectations.
type FileScannerMockMethods struct {
	Next *_imptest.DependencyMethod
	Err  *_imptest.DependencyMethod
}

// FileScannerMockNextCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileScannerMockNextCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileScannerMockNextCall) InjectReturnValues(result0 filesystem.FileInfo, result1 bool) {
	c.DependencyCall.InjectReturnValues(result0, result1)
}

// MockFileScanner creates a new FileScannerMockHandle for testing.
func MockFileScanner(t _imptest.TestReporter) *FileScannerMockHandle {
	ctrl := _imptest.NewImp(t)
	methods := &FileScannerMockMethods{
		Next: _imptest.NewDependencyMethod(ctrl, "Next"),
		Err:  _imptest.NewDependencyMethod(ctrl, "Err"),
	}
	h := &FileScannerMockHandle{
		Method:     methods,
		Controller: ctrl,
	}
	h.Mock = &mockFileScannerImpl{handle: h}
	return h
}

// mockFileScannerImpl implements filesystem.FileScanner.
type mockFileScannerImpl struct {
	handle *FileScannerMockHandle
}

// Err implements filesystem.FileScanner.Err.
func (impl *mockFileScannerImpl) Err() error {
	call := &_imptest.GenericCall{
		MethodName:   "Err",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}

// Next implements filesystem.FileScanner.Next.
func (impl *mockFileScannerImpl) Next() (filesystem.FileInfo, bool) {
	call := &_imptest.GenericCall{
		MethodName:   "Next",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.handle.Controller.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 filesystem.FileInfo
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(filesystem.FileInfo); ok {
			result1 = value
		}
	}

	var result2 bool
	if len(resp.ReturnValues) > 1 {
		if value, ok := resp.ReturnValues[1].(bool); ok {
			result2 = value
		}
	}

	return result1, result2
}
