// Code generated by impgen. DO NOT EDIT.

package filesystem

import (
	_imptest "github.com/toejough/imptest/imptest"
)

// SFTPClientCloserMock is the mock for SFTPClientCloser.
type SFTPClientCloserMock struct {
	imp   *_imptest.Imp
	Close *_imptest.DependencyMethod
}

// Interface returns the SFTPClientCloser implementation that can be passed to code under test.
func (m *SFTPClientCloserMock) Interface() SFTPClientCloser {
	return &mockSFTPClientCloserImpl{mock: m}
}

// SFTPClientCloserMockCloseCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type SFTPClientCloserMockCloseCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *SFTPClientCloserMockCloseCall) InjectReturnValues(result0 error) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockSFTPClientCloser creates a new SFTPClientCloserMock for testing.
func MockSFTPClientCloser(t _imptest.TestReporter) *SFTPClientCloserMock {
	imp := _imptest.NewImp(t)
	return &SFTPClientCloserMock{
		imp:   imp,
		Close: _imptest.NewDependencyMethod(imp, "Close"),
	}
}

// mockSFTPClientCloserImpl implements SFTPClientCloser.
type mockSFTPClientCloserImpl struct {
	mock *SFTPClientCloserMock
}

// Close implements SFTPClientCloser.Close.
func (impl *mockSFTPClientCloserImpl) Close() error {
	call := &_imptest.GenericCall{
		MethodName:   "Close",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 error
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(error); ok {
			result1 = value
		}
	}

	return result1
}
