// Code generated by impgen. DO NOT EDIT.

package filesystem_test

import (
	_imptest "github.com/toejough/imptest/imptest"
	fs "io/fs"
	time "time"
)

// FileInfoMock is the mock for FileInfo.
type FileInfoMock struct {
	imp     *_imptest.Imp
	Name    *_imptest.DependencyMethod
	Size    *_imptest.DependencyMethod
	Mode    *_imptest.DependencyMethod
	ModTime *_imptest.DependencyMethod
	IsDir   *_imptest.DependencyMethod
	Sys     *_imptest.DependencyMethod
}

// Interface returns the FileInfo implementation that can be passed to code under test.
func (m *FileInfoMock) Interface() fs.FileInfo {
	return &mockFileInfoImpl{mock: m}
}

// FileInfoMockIsDirCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockIsDirCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockIsDirCall) InjectReturnValues(result0 bool) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileInfoMockModTimeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockModTimeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockModTimeCall) InjectReturnValues(result0 time.Time) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileInfoMockModeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockModeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockModeCall) InjectReturnValues(result0 fs.FileMode) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileInfoMockNameCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockNameCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockNameCall) InjectReturnValues(result0 string) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileInfoMockSizeCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockSizeCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockSizeCall) InjectReturnValues(result0 int64) {
	c.DependencyCall.InjectReturnValues(result0)
}

// FileInfoMockSysCall wraps DependencyCall with typed GetArgs and InjectReturnValues.
type FileInfoMockSysCall struct {
	*_imptest.DependencyCall
}

// InjectReturnValues specifies the typed values the mock should return.
func (c *FileInfoMockSysCall) InjectReturnValues(result0 any) {
	c.DependencyCall.InjectReturnValues(result0)
}

// MockFileInfo creates a new FileInfoMock for testing.
func MockFileInfo(t _imptest.TestReporter) *FileInfoMock {
	imp := _imptest.NewImp(t)
	return &FileInfoMock{
		imp:     imp,
		Name:    _imptest.NewDependencyMethod(imp, "Name"),
		Size:    _imptest.NewDependencyMethod(imp, "Size"),
		Mode:    _imptest.NewDependencyMethod(imp, "Mode"),
		ModTime: _imptest.NewDependencyMethod(imp, "ModTime"),
		IsDir:   _imptest.NewDependencyMethod(imp, "IsDir"),
		Sys:     _imptest.NewDependencyMethod(imp, "Sys"),
	}
}

// mockFileInfoImpl implements fs.FileInfo.
type mockFileInfoImpl struct {
	mock *FileInfoMock
}

// IsDir implements fs.FileInfo.IsDir.
func (impl *mockFileInfoImpl) IsDir() bool {
	call := &_imptest.GenericCall{
		MethodName:   "IsDir",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 bool
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(bool); ok {
			result1 = value
		}
	}

	return result1
}

// ModTime implements fs.FileInfo.ModTime.
func (impl *mockFileInfoImpl) ModTime() time.Time {
	call := &_imptest.GenericCall{
		MethodName:   "ModTime",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 time.Time
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(time.Time); ok {
			result1 = value
		}
	}

	return result1
}

// Mode implements fs.FileInfo.Mode.
func (impl *mockFileInfoImpl) Mode() fs.FileMode {
	call := &_imptest.GenericCall{
		MethodName:   "Mode",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 fs.FileMode
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(fs.FileMode); ok {
			result1 = value
		}
	}

	return result1
}

// Name implements fs.FileInfo.Name.
func (impl *mockFileInfoImpl) Name() string {
	call := &_imptest.GenericCall{
		MethodName:   "Name",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 string
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(string); ok {
			result1 = value
		}
	}

	return result1
}

// Size implements fs.FileInfo.Size.
func (impl *mockFileInfoImpl) Size() int64 {
	call := &_imptest.GenericCall{
		MethodName:   "Size",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 int64
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(int64); ok {
			result1 = value
		}
	}

	return result1
}

// Sys implements fs.FileInfo.Sys.
func (impl *mockFileInfoImpl) Sys() any {
	call := &_imptest.GenericCall{
		MethodName:   "Sys",
		Args:         []any{},
		ResponseChan: make(chan _imptest.GenericResponse, 1),
	}
	impl.mock.imp.CallChan <- call
	resp := <-call.ResponseChan
	if resp.Type == "panic" {
		panic(resp.PanicValue)
	}

	var result1 any
	if len(resp.ReturnValues) > 0 {
		if value, ok := resp.ReturnValues[0].(any); ok {
			result1 = value
		}
	}

	return result1
}
