// Code generated by impgen. DO NOT EDIT.

package config

import (
	_imptest "github.com/toejough/imptest/imptest"
	_reflect "reflect"
)

// WrapPostProcessConfigCallHandle represents a single call to the wrapped function.
type WrapPostProcessConfigCallHandle struct {
	*_imptest.CallableController[WrapPostProcessConfigReturnsReturn]
	controller        *_imptest.TargetController
	pendingCompletion *_imptest.PendingCompletion
	// Eventually is the async version of this call handle for registering non-blocking expectations.
	Eventually *WrapPostProcessConfigCallHandleEventually
}

// ExpectPanicEquals verifies the function panics with the expected value.
func (h *WrapPostProcessConfigCallHandle) ExpectPanicEquals(expected any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, expected)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectPanicMatches verifies the function panics with a value matching the given matcher.
func (h *WrapPostProcessConfigCallHandle) ExpectPanicMatches(matcher any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Panicked != nil {
		ok, msg := _imptest.MatchValue(h.Panicked, matcher)
		if !ok {
			h.T.Fatalf("panic value: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to panic, but it returned")
}

// ExpectReturnsEqual verifies the function returned the expected values.
func (h *WrapPostProcessConfigCallHandle) ExpectReturnsEqual(v0 *Config, v1 error) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		if !_reflect.DeepEqual(h.Returned.Result0, v0) {
			h.T.Fatalf("expected return value 0 to be %v, got %v", v0, h.Returned.Result0)
		}
		if !_reflect.DeepEqual(h.Returned.Result1, v1) {
			h.T.Fatalf("expected return value 1 to be %v, got %v", v1, h.Returned.Result1)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// ExpectReturnsMatch verifies the return values match the given matchers.
func (h *WrapPostProcessConfigCallHandle) ExpectReturnsMatch(v0 any, v1 any) {
	h.T.Helper()
	h.WaitForResponse()

	if h.Returned != nil {
		var ok bool
		var msg string
		ok, msg = _imptest.MatchValue(h.Returned.Result0, v0)
		if !ok {
			h.T.Fatalf("return value 0: %s", msg)
		}
		ok, msg = _imptest.MatchValue(h.Returned.Result1, v1)
		if !ok {
			h.T.Fatalf("return value 1: %s", msg)
		}
		return
	}

	h.T.Fatalf("expected function to return, but it panicked with: %v", h.Panicked)
}

// WrapPostProcessConfigCallHandleEventually wraps a call handle for async expectation registration.
type WrapPostProcessConfigCallHandleEventually struct {
	h *WrapPostProcessConfigCallHandle
}

// ExpectPanicEquals registers an async expectation for a panic value.
func (e *WrapPostProcessConfigCallHandleEventually) ExpectPanicEquals(value any) {
	e.ensureStarted().ExpectPanicEquals(value)
}

// ExpectReturnsEqual registers an async expectation for return values.
func (e *WrapPostProcessConfigCallHandleEventually) ExpectReturnsEqual(values ...any) {
	e.ensureStarted().ExpectReturnsEqual(values...)
}

func (e *WrapPostProcessConfigCallHandleEventually) ensureStarted() *_imptest.PendingCompletion {
	if e.h.pendingCompletion == nil {
		e.h.pendingCompletion = e.h.controller.RegisterPendingCompletion()
		go func() {
			e.h.WaitForResponse()
			e.h.pendingCompletion.SetCompleted(e.h.Returned, e.h.Panicked)
		}()
	}
	return e.h.pendingCompletion
}

// WrapPostProcessConfigReturnsReturn holds the return values from the wrapped function.
type WrapPostProcessConfigReturnsReturn struct {
	Result0 *Config
	Result1 error
}

// WrapPostProcessConfigWrapperHandle is the test handle for a wrapped function.
type WrapPostProcessConfigWrapperHandle struct {
	Method     *WrapPostProcessConfigWrapperMethod
	Controller *_imptest.TargetController
}

// WrapPostProcessConfigWrapperMethod wraps a function for testing.
type WrapPostProcessConfigWrapperMethod struct {
	t          _imptest.TestReporter
	controller *_imptest.TargetController
	callable   func(*Config) (*Config, error)
}

// Start executes the wrapped function in a goroutine.
func (m *WrapPostProcessConfigWrapperMethod) Start(cfg *Config) *WrapPostProcessConfigCallHandle {
	handle := &WrapPostProcessConfigCallHandle{
		CallableController: _imptest.NewCallableController[WrapPostProcessConfigReturnsReturn](m.t),
		controller:         m.controller,
	}
	handle.Eventually = &WrapPostProcessConfigCallHandleEventually{h: handle}
	go func() {
		defer func() {
			if r := recover(); r != nil {
				handle.PanicChan <- r
			}
		}()
		ret0, ret1 := m.callable(cfg)
		handle.ReturnChan <- WrapPostProcessConfigReturnsReturn{Result0: ret0, Result1: ret1}
	}()
	return handle
}

// WrapPostProcessConfig wraps a function for testing.
func WrapPostProcessConfig(t _imptest.TestReporter, fn func(*Config) (*Config, error)) *WrapPostProcessConfigWrapperHandle {
	ctrl := _imptest.NewTargetController(t)
	return &WrapPostProcessConfigWrapperHandle{
		Method: &WrapPostProcessConfigWrapperMethod{
			t:          t,
			controller: ctrl,
			callable:   fn,
		},
		Controller: ctrl,
	}
}
